version: "3.5"
services:
  teslamate:
    image: "teslamate/teslamate:latest"
    restart: always
    environment:
      - ENCRYPTION_KEY=
      - DATABASE_USER=teslamate
      - DATABASE_PASS=
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    volumes:
      - "tesla_data:/opt/app/import"
  database:
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=teslamate
    volumes:
      - "teslamate-db:/var/lib/postgresql/data"
  grafana:
    image: "teslamate/grafana:latest"
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    volumes:
      - "teslamate-grafana-data:/var/lib/grafana"
  mosquitto:
    image: "eclipse-mosquitto:2"
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - "mosquitto-conf:/mosquitto/config"
      - "mosquitto-data:/mosquitto/data"
volumes:
  teslamate-db: {}
  teslamate-grafana-data: {}
  mosquitto-conf: {}
  mosquitto-data: {}
  tesla_data: {}
